### ISSUE TITLE
Please add source code and reference to my repository

### ISSUE THREAD

**Issue by psxdev** [Hackinside/PS5_camera_files#1]
Please  original source and work on this is my repository i dont want receive disclaimers from others parties or legal issues.

If you makes changes in source please include it.

https://github.com/psxdev/OrbisEyeCam

**Comment by Hackinside** [comment]
Sure...

**Comment by conorburcher** [comment]
hey I'm having issues, I downloaded the zip and extracted files, ran the updater, connected the camera, and then followed all other steps, but whenever I select the camera for use in obs or discord it doesn't show a picture and just shows an orange square, I don't know what I'm doing wrong
