### ISSUE TITLE
Resolution?

### ISSUE THREAD

**Issue by dualdragoon** [Hackinside/PS5_camera_files#11]
So pretty much everywhere I find this camera online claims that it's an HD 1080p camera yet when I use it with these drivers it comes in at a whopping 448x256 per lens. So is the description of the camera a lie literally everywhere or is something screwed in my setup?

**Comment by Hackinside** [comment]
What software are you using to get that setting? In my setup, when using the OBS Studio, I can tweak the camera settings by choosing the desired resolution, exposure and so on. Then I activate the OBS Virtual Camera for using it on other apps or streaming.
For deep detail about the camera driver development, you can visit the developer page [here]( https://psxdev.github.io/luke2.html )

**Comment by dualdragoon** [comment]
I'm using OBS and sized the output to source but the source is only 448x256 per lens.

**Comment by Hackinside** [comment]
Well, I'm using OBS Studio 27.2.4 version. If you go to the camera properties and look for the resolution/FPS Type, change it from Default to Custom. See the picture.
![Example image](https://user-images.githubusercontent.com/37005360/176680379-00c6fe00-1d91-492d-bee3-3278fc111f81.png)

**Comment by Celppu** [comment]
The problem still exists. For some reason windows 10 camera app can use all the available resolutions, but opencv can only see the smallest possible setting
