### ISSUE TITLE
Dark Video Output on PS5 Camera

### ISSUE THREAD

**Issue by PavlikBender** [Hackinside/PS5_camera_files#19]
I found good issue on psxdev/OrbisEyeCam about dark output https://github.com/psxdev/OrbisEyeCam/issues/10
and mister [Lightbass](https://github.com/Lightbass) send [link of firmware with enabled autoexposure](https://github.com/prosperodev/hdcamera/files/11412232/firmware_discord_and_gamma_fix.zip).
Hackinside, maybe you should update firmware.bin file in your repository?

**Comment by PavlikBender** [comment]
Yes, it worked for me. I've checked today this firmware file.

**Comment by Hackinside** [comment]
> Yes, it worked for me. I've checked today this firmware file.

I saw that fix a while ago but never had a chance to test it. 
Thank you again. I'll now close this issue.

**Comment by PavlikBender** [comment]
https://github.com/psxdev/OrbisEyeCam/issues/10#issuecomment-2295908175
