### ISSUE TITLE
Unknown Error Jur Jur

### ISSUE THREAD

**Issue by AbdelNabut** [Hackinside/PS5_camera_files#2]
Phase 2 read failed received 0 bytes instead of 512.
I ran InstallDriver.exe then the OrbusEyeCameraFirmwareLoader and I'm getting this error.

Firmware.bin is in the same folder as the OrbusEyeCameraFirmwareLoader

**Comment by Hackinside** [comment]
Can you see in the device manager, USB Camera-OV580 under cameras?
Do you have any antivirus installed?

**Comment by AbdelNabut** [comment]
I don’t see usb camera, but I do see the USB Boot under Universal Serial Bus devices. I just have Windows Security bundled with Windows, but it usually alerts me when a threat has been managed. And nothing is showing in the protection history. A bit of a stretch, but could the issue be a lack of compatibility with windows 11.

~ Abdel Nabut
________________________________

**Comment by Hackinside** [comment]
It should work using Windows 11. Maybe the USB controller. 
Under Universal Serial Bus Controller, what is the USB 3.0 controller do you have installed?
I'm using the Intel(R) USB 3.0 eXtensible Host Controller - 1.0 (Microsoft) in one machine and  Intel(R) USB 3.20 eXtensible Host Controller - 1.20 (Microsoft) in another. Both desktop PC and working fine,
Someone reported the same issue but for some reason the issue has been fixed itself.

**Comment by AbdelNabut** [comment]
I’ve got the 3.10. Could that be the issue?

~ Abdel Nabut
________________________________

**Comment by thematrixduo** [comment]
same error here. I'm using the Intel(R) USB 3.0 eXtensible Host Controller - 1.0 (Microsoft)

**Comment by Hackinside** [comment]
I found what could be the reason for this error: See my new [Youtube Video](https://youtu.be/1yr6Ytqfu4w)
