### ISSUE TITLE
attempted install over USB 2

### ISSUE THREAD

**Issue by KristophTahti** [Hackinside/PS5_camera_files#3]
This is the first time I've done anything like this, complete noob.

 I connected the HD camera to my USB 2 port on the computer without realizing it was a USB 3 cable.
Not only does the camera not work with Windows, it now doesn't work with the PS5 either.

I guess I can use the same code to fix it (if I can connect to usb 3) now I just need to find a copy of the original firmware. 

Any advice would be greatly appreciated.

**Comment by fallXone** [comment]
This is the same exact issue i'm having @Hackinside , so looks like it has happened before.

**Comment by Hackinside** [comment]
It happens before, but I don't think it is related to the Windows drivers. 
Check the following forum:
https://www.reddit.com/r/PS5/comments/jt3slc/ps5_webcam_not_connecting_to_ps5_please_help/

**Comment by fallXone** [comment]
> It has happened before but doesn't relate to the Windows drivers. Check the following forum: https://www.reddit.com/r/PS5/comments/jt3slc/ps5_webcam_not_connecting_to_ps5_please_help/

most of these people were selecting the PS4 camera and not the HD camera. My camera not working is 100% related to attempting to do this, and is not just some fluke thing. Seems that something got corrupted inside the camera. @KristophTahti  were you ever able to find a fix for this?
