### ISSUE TITLE
Driver not responding to activation calls

### ISSUE THREAD

**Issue by MaximusX800** [Hackinside/PS5_camera_files#4]
While everything works, it seems like the driver call to activate the camera in some software, like OBS and Nvidia Broadcast, does not activate correctly.  This can be forced with say using the Windows 10/11 camera app, once this happens, the camera feed will work normally in those apps.

**Comment by Hackinside** [comment]
Contact the Windows driver developer [here](https://github.com/psxdev/OrbisEyeCam)
