### ISSUE TITLE
Settings app?

### ISSUE THREAD

**Issue by Lightbass** [Hackinside/PS5_camera_files#5]
Hello.

Maybe make some settings app?
For set default resolution?
Or recommendation for this case?

For example, in discord this web cam work badly.

**Comment by Hackinside** [comment]
Well, it needs some developer interested to do it. At the moment you can use OBS Studio or Manycam to create a virtual camera. I don't know another solution at the moment.

**Comment by robinkoehler** [comment]
Is there a way to tap into the default windows webcam settings dialogue? The one that pops up in OBS when clicking on "configure video" (attached)?
![ConfigureVideo](https://user-images.githubusercontent.com/43112840/147436298-56ea5c06-1f44-4b32-8532-59993008e1c5.png)

**Comment by Hackinside** [comment]
> Is there a way to tap into the default windows webcam settings dialogue? The one that pops up in OBS when clicking on "configure video" (attached)? ![ConfigureVideo](https://user-images.githubusercontent.com/43112840/147436298-56ea5c06-1f44-4b32-8532-59993008e1c5.png)

The Windows Camera app is very limited. Only via a third-party app, I presume.

**Comment by robinkoehler** [comment]
I'm just asking at this point if there is a way to invoke this specific dialogue box from your driver (without a third party app, or without OBS / windows camera). This alone would fulfil a lot of requirements I'd assume

**Comment by Hackinside** [comment]
> I'm just asking at this point if there is a way to invoke this specific dialogue box from your driver (without a third party app, or without OBS / windows camera). This alone would fulfil a lot of requirements I'd assume

The driver has been developed by https://github.com/psxdev/ Give him a shout.

Original dev page: https://github.com/psxdev/OrbisEyeCam

**Comment by robinkoehler** [comment]
Ok thank you! I didn't realise that this would be the right person to contact in this regard. Appreciate the information
