### ISSUE TITLE
Too dark

### ISSUE THREAD

**Issue by dualdragoon** [Hackinside/PS5_camera_files#6]
For some reason the camera on my win 10 pc is incredibly dark. Like barely able to see anything in a well lit room. Can't seem to figure out how to make it any brighter.

**Comment by puga292** [comment]
Did it look kinda green? I had the same issue, but with Streamlabs OBS software I was able to figure out that the exposure was just set to -4 or so, turning it back to -1 or 0 fixed it and it looked great.

**Comment by dualdragoon** [comment]
Nope. Just really dark. Like the camera was in a dark room even in full light.

**Comment by kloklojul** [comment]
I had the same issue. Whenever the camera is too dark you have to set the brightness up. if it already is at max you have to move the slider back down and than back up again.

**Comment by dualdragoon** [comment]
Hmm. I don't have the built in win 10 camera app because of the specific version of win 10 I'm using and as near as I could tell that's not a driver level option so I'm not sure how I could do that.

**Comment by Hackinside** [comment]
I believe that the camera default settings is to be in low exposure, because it needs to pick up the psvr glasses and move controller lights only. Maybe the firmware holds this default settings.

**Comment by dualdragoon** [comment]
Unfortunately that's not something easy to edit.

**Comment by sl0sh** [comment]
yeah it looks crappy

**Comment by Hackinside** [comment]
I believe It is dark because of the original firmware uploaded to the camera. This firmware is pulled from a Playstation console which is supposed to hold the default configuration to capture the lights from the VR headset and controllers. The Windows Camera app lacks video settings options.  At the moment you need to rely on some software to filter the camera settings and create a virtual camera, like OBS, Manycam, Nvidia broadcast and others.

**Comment by Andr3wi77e** [comment]
I found a working way. Launch the Camera application on Windows (there the camera works as well). In OBS, grab the Camera window, transform the output to remove the application interface, click "Launch Virtual Camera". In the desired application as discord, select "OBS Virtiual Camera" as the camera
