### ISSUE TITLE
Ps5 Camera

### ISSUE THREAD

**Issue by Parisio2003** [Hackinside/PS5_camera_files#8]
Hy!

I have a problem with my ps5 camera. I wanted to use it on my pc. I saw the post from hackinside on how to do this. So this is what i did.
1. I installed the referenced drivers 
2. I plugged in the camera
3. Then I run the OrbisEyeCameraFirmwareLoader.exe file
4. I double click on it
5. The only thing that happens is that I get I get a short flash on my taskbar en than nothing. 
So nothing happens my pc doesn't recognize it as a camera.

Can someone help me?

Wannes Parijs

**Comment by Hackinside** [comment]
Does the camera shows in the device manager?
The camera needs to be connected to an USB3.0 port.
There are an issue connecting it to USB 2.0, 3.1 and 3.2.

The drivers developer @psxdev did not update it yet.

Try it in all ports.
________________________________
From: Parisio2003 ***@***.***>
Sent: Sunday, April 3, 2022 10:37:40 PM
To: Hackinside/PS5_camera_files ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hackinside/PS5_camera_files] Ps5 Camera (Issue #8)


Hy!

I have a problem with my ps5 camera. I wanted to use it on my pc. I saw the post from hackinside on how to do this. So this is what i did.

  1.  I installed the referenced drivers
  2.  I plugged in the camera
  3.  Then I run the OrbisEyeCameraFirmwareLoader.exe file
  4.  I double click on it
  5.  The only thing that happens is that I get I get a short flash on my taskbar en than nothing.
So nothing happens my pc doesn't recognize it as a camera.

Can someone help me?

Wannes Parijs

**Comment by Parisio2003** [comment]
Now I put it in usb 3.0 but I only have 1 usb 3.0 port on the front panel of my pc. So it's very messy with cables if I do it like this. Is it possible to use ubs 2.0 cuz that are the other ports that my pc has and those are on the back of my pc.

**Comment by Hackinside** [comment]
The camera is only compatible with USB 3.0. it is better when connected at the back of your computer.
If your pc have a usb 3.0 at the front, it should do have at the back too.
Download the USB device tree viewer on
https://www.uwe-sieber.de/usbtreeview_e.html
To identify the port you are connecting to.

________________________________

**Comment by Parisio2003** [comment]
I downloaded it but apparently i have only a usb 3.0 at the front, on the back i have 4 usb 2.0 ports.
The camera works now with the usb 3.0 port but when i want to make a call for example with messenger the video is very stuttering. When I open the default camera app from windows i dont have that issue. Im connected through ethernet so thats not the problem. when i open zoom and go to the zoom settings i dont have that problem either . But with messenger and discord ia have the same issue. When i open discord in the settings to the video settings the image is very stuttering with a lot of horizontal stripes.

**Comment by Hackinside** [comment]
Try the OBS Studio virtual camera method.

Add the camera to OBS, crop the image and start the virtual camera. On zoom or other communication chat, choose the OBS virtual camera.
________________________________

**Comment by Parisio2003** [comment]
i installed the obs program but now if open the software i got 2 video signals of my self cause the camera has two lenses wo how do i get one video signal of myself?

**Comment by Hackinside** [comment]
See my videos about the PS4 camera installation

https://youtu.be/1yr6Ytqfu4w

________________________________
