### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by neutral8l** [Hackinside/PS5_camera_files#9]
The camera is detected, but the image freezes and is not displayed
![Снимок экрана 2022-04-07 140722](https://user-images.githubusercontent.com/102918296/162185685-6cdd3590-1a68-4633-8903-110653286d4d.png)
![Снимок экрана 2022-04-07 140842](https://user-images.githubusercontent.com/102918296/162185833-69b0c894-ed3b-4f38-9ca6-3dab1c1e93e7.png)
.

**Comment by Hackinside** [comment]
Have you tried the new installer?

________________________________
From: neutral8l ***@***.***>
Sent: Thursday, April 7, 2022 12:01:55 PM
To: Hackinside/PS5_camera_files ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hackinside/PS5_camera_files] Does not work. (Issue #9)


The camera is detected, but the image freezes and is not displayed.

**Comment by neutral8l** [comment]
YE
![Снимок экрана 2022-04-07 145900](https://user-images.githubusercontent.com/102918296/162193711-670ebc59-95cd-412a-a38f-fcf94a4dcfc7.png)
![Снимок экрана 2022-04-07 145953](https://user-images.githubusercontent.com/102918296/162193866-cc3f05e5-a152-43d0-a877-1ac625379bb4.png)
S
